### PR TITLE
Make error messages less annoying

### LINKED ISSUE #11: Obnoxious Error Messages
While it's a perfectly correct statement, it's annoying to have to click it.  Here are some ideas I had about fixing it:
- Automatically deselecting nodes you don't own
- Replacing the dialog box with temporary text on the screen

### PR DESCRIPTION
**Pull request by riftEmber**
Fixes #11

### CODE REVIEW

**Comment by riftEmber** [comment]
Let me know if you think it looks alright

**Comment by vpzomtrrfrt** [comment]
It looks like it works, but I'm not sure it's obvious enough.  I might have missed it if I wasn't expecting an error.

**Comment by riftEmber** [comment]
Ok, is this better?

**Comment by vpzomtrrfrt** [comment]
A little

**Comment by riftEmber** [comment]
Better enough?

**Comment by vpzomtrrfrt** [comment]
For now, I gues

**Comment by riftEmber** [comment]
Merging then

**Pull request merged**
